# Generated by Django 5.1.1 on 2024-11-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_rename_usuario_pedido_cliente_and_more'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='pedidos.PedidoProducto', to='producto.producto'),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
